#!/usr/bin/python

import sys
import struct
from urllib import urlencode
from urllib2 import urlopen

BASE_URL = "http://geoffrey.co/api/session/{}/{}/confirm?{}"


def generate(response=False):
    sys.stdout.write(struct.pack('>hh', 2, int(response is True)))
    sys.stdout.flush()


class NotImplementedMethod(Exception):
    pass


def main():
    try:
        while True:
            # Verify the information checks out
            try:
                length = sys.stdin.read(2)
                size = struct.unpack('>h', length)[0]
                inpt = sys.stdin.read(size).split(':')
                operation = inpt.pop(0)
                if operation == 'auth':
                    username, host, password = inpt
                    skey, pkey = password.split("@", 1)
                    url = BASE_URL.format(pkey, skey,
                                          urlencode({"username": username,
                                                     "chat_domain": host}))
                    req = urlopen(url)
                    generate(req.read() == 'true')
                else:
                    # raise to make sure we reply
                    raise NotImplementedMethod()
            except Exception:
                generate(False)

    except KeyboardInterrupt:
        raise SystemExit(0)


if __name__ == "__main__":
    main()
